Added higher resolution screenshot
SSWConsulting/SSW.Rules.Content pull request #1328
Opened 2021-07-14 01:52 UTC by taineriley1

The previous screenshot in this rule was low resolution and therefore didn't extend across the width of the screen.
![image](https://user-images.githubusercontent.com/40375803/125548009-4ac0b748-fb84-4070-9419-9e669c8cdea1.png)
**Figure: Screenshot does not fit screen width**

A higher resolution screenshot with similar content was added.

2021-07-14 23:05 UTC, bradystroud requested changes

2021-07-14 23:05 UTC, bradystroud commented on rules/declare-member-accessibility-for-all-classes/rule.md
> +**Figure: Compiler warning given for not explicitly defining member access level**
Also check that the warning in the image is relevant to the rule

2021-07-19 00:55 UTC, taineriley1 commented on rules/declare-member-accessibility-for-all-classes/rule.md
> +**Figure: Compiler warning given for not explicitly defining member access level**
Done - see latest commit

2021-07-19 00:56 UTC, bradystroud approved these changes

2021-07-19 00:56 UTC, merged