Update rule.md
SSWConsulting/SSW.Rules.Content pull request #1545
Opened 2021-08-12 09:08 UTC by taineriley1

2021-08-12 23:09 UTC, pierssinclairssw requested changes

2021-08-12 23:09 UTC, pierssinclairssw commented on rules/craft-and-deliver-engaging-presentations/rule.md
> +  - basic-dos-and-don'ts-of-presenting
What's going on here, looks like something strange has happend.

2021-08-12 23:40 UTC, taineriley1 commented on rules/craft-and-deliver-engaging-presentations/rule.md
> +  - basic-dos-and-don'ts-of-presenting
Good observation, now resolved

2021-08-13 00:20 UTC, pierssinclairssw approved these changes

2021-08-13 00:20 UTC, merged