Jakebayliss patch 2
SSWConsulting/SSW.Rules.Content pull request #1818
Opened 2021-09-27 06:55 UTC by jakebayliss

2021-09-27 07:20 UTC, pierssinclairssw requested changes

2021-09-27 07:20 UTC, pierssinclairssw commented on rules/do-you-know-how-to-programmatically-get-git-commits/rule.md
> + **Figure: HTTPS GET commits from your repository**
Figure should be inside the [ ]

2021-09-27 07:20 UTC, pierssinclairssw commented on rules/do-you-know-how-to-programmatically-get-git-commits/rule.md
>   **Figure: Using the Chrome extension Postman to execute our request with Basic Authentication**
see above

2021-09-27 07:39 UTC, jakebayliss commented on rules/do-you-know-how-to-programmatically-get-git-commits/rule.md
> + **Figure: HTTPS GET commits from your repository**
Done

2021-09-27 07:39 UTC, jakebayliss commented on rules/do-you-know-how-to-programmatically-get-git-commits/rule.md
>   **Figure: Using the Chrome extension Postman to execute our request with Basic Authentication**
Done

2021-09-28 07:22 UTC, pierssinclairssw approved these changes

2021-09-28 07:23 UTC, merged