updated URL
SSWConsulting/SSW.Rules.Content pull request #2279
Opened 2021-12-21 11:26 UTC by tiagov8

2021-12-24 00:28 UTC, JackDevAU approved these changes

2021-12-24 01:28 UTC, tiagov8 commented
Hey @JackDevAU did you follow up this build error?

2021-12-24 03:54 UTC, pierssinclairssw approved these changes

2021-12-24 03:55 UTC, pierssinclairssw requested changes
Sorry approved without seeing the failed check. Check needs to be fixed

2021-12-24 04:38 UTC, JackDevAU commented
> Hey @JackDevAU did you follow up this build error?

Hey @tiagov8,
I'm currently investigating. This looks to be an issue with the GitHub Action we are using. From this issue https://github.com/trilom/file-changes-action/issues/104 It seems upgrading to version `1.2.4` should fix it. (We are currently using `1.2.3`) 
I'll let you when this has been updated.

2021-12-24 08:03 UTC, JackDevAU approved these changes

2021-12-24 12:52 UTC, adamcogan approved these changes

2021-12-31 04:40 UTC, adamcogan approved these changes

2021-12-31 04:43 UTC, merged