Update Rule “azure-certifications-and-associated-exams/rule”
SSWConsulting/SSW.Rules.Content pull request #2334
Opened 2022-01-10 22:08 UTC by brydeno

Automatically generated by Netlify CMS

2022-01-10 22:09 UTC, JackDevAU approved these changes

2022-01-11 03:34 UTC, bradystroud requested changes

2022-01-11 03:34 UTC, bradystroud commented on rules/azure-certifications-and-associated-exams/rule.md
>  Earn this certification to prove you have a foundational knowledge of cloud services and how those services are provided with Microsoft Azure.
I don't think this sentence makes sense after the changes above
```suggestion
Earn this certification to prove you have a foundational knowledge of the Power Platform and how to build solutions using these services.
```

2022-01-11 03:34 UTC, bradystroud commented on rules/azure-certifications-and-associated-exams/rule.md
>  If you're just getting started,  take a look at:
```suggestion
If you're just getting started, take a look at:
```

2022-01-16 21:33 UTC, leahy268 approved these changes

2022-01-31 04:12 UTC, merged