Update Rule “dones-do-you-use-email-for-tasks-only-not-communication/rule”
SSWConsulting/SSW.Rules.Content pull request #2493
Opened 2022-02-28 00:35 UTC by AshAnil

Automatically generated by Netlify CMS

2022-02-28 00:44 UTC, chrisschultzssw approved these changes
Good change!

2022-02-28 06:48 UTC, Hona submitted a review, later dismissed
Remove the trailing slashes from netlify.

Happens with the ::: frontmatter blocks

2022-02-28 06:49 UTC, JackDevAU requested changes

2022-02-28 06:49 UTC, JackDevAU commented on rules/dones-do-you-use-email-for-tasks-only-not-communication/rule.md
> +::: email-template\
Please remove the trailing slash's in this file  i.e.`\`  (This is a bug with Netlify 😟)

2022-02-28 06:49 UTC, JackDevAU commented on rules/dones-do-you-use-email-for-tasks-only-not-communication/rule.md
> +| Subject: | What do you think? |\
here

2022-02-28 06:49 UTC, JackDevAU commented on rules/dones-do-you-use-email-for-tasks-only-not-communication/rule.md
> +:::\
here

2022-02-28 06:49 UTC, JackDevAU commented on rules/dones-do-you-use-email-for-tasks-only-not-communication/rule.md
> +::: email-template\
here

2022-02-28 06:49 UTC, JackDevAU commented on rules/dones-do-you-use-email-for-tasks-only-not-communication/rule.md
> +::: good\
here

2022-03-01 01:09 UTC, JackDevAU approved these changes

2022-03-01 01:12 UTC, merged