Update Rule “no-hello/rule”
SSWConsulting/SSW.Rules.Content pull request #2538
Opened 2022-03-07 01:09 UTC by jontygardner

Automatically generated by Netlify CMS

2022-03-07 17:33 UTC, tiagov8 requested changes
Hey @jontygardner 

1. Please see https://www.ssw.com.au/rules/rule/ on how to embed a video on a rule and fix your Markdown
2. Add the video after the 2 introductory paragraphs
3. Change from "Figure: ..." to "Video: ..."
4. Update your PR
5. Add me as a reviewer

2022-03-15 20:52 UTC, tiagov8 commented
Hi @jontygardner 

1. Not done - see this link: https://www.ssw.com.au/rules/rule#videos
    It shows exactly **how to** embed a video in Rules (Tip: No HTML iframe)

2. On the example, fix 
    > See email subjecT:
    
    to
    > See email subject:

2022-03-15 22:38 UTC, AshAnil approved these changes
👍 💯

2022-03-21 01:02 UTC, tiagov8 approved these changes

2022-03-21 01:03 UTC, merged