Update Rule “involve-all-stakeholders/rule”
SSWConsulting/SSW.Rules.Content pull request #2989
Opened 2022-04-28 10:51 UTC by KostaMadorsky

Automatically generated by Netlify CMS

2022-04-28 20:07 UTC, bradystroud requested changes

2022-04-28 20:07 UTC, bradystroud commented on rules/involve-all-stakeholders/rule.md
> +title: Do you make sure that all stakeholders are involved in the Specification
This is still a question 
```suggestion
title: Do you make sure that all stakeholders are involved in the Specification?
```

2022-04-28 22:58 UTC, adamcogan approved these changes

2022-04-29 02:38 UTC, leahy268 approved these changes

2022-05-03 01:48 UTC, bradystroud approved these changes

2022-05-03 01:48 UTC, merged