fixed capitalization
SSWConsulting/SSW.Rules.Content pull request #2996
Opened 2022-04-28 17:25 UTC by tiagov8

2022-04-28 20:10 UTC, bradystroud requested changes

2022-04-28 20:10 UTC, bradystroud commented on rules/triaging-do-you-understand-that-all-feedback-will-be-worked-on-in-the-next-sprint/rule.md
> +title: Triaging - Do you understand that all deedback will be worked on in the next Sprint?
Typo 
```suggestion
title: Triaging - Do you understand that all feedback will be worked on in the next Sprint?
```

2022-04-29 15:32 UTC, adamcogan approved these changes

2022-04-29 18:13 UTC, bradystroud approved these changes

2022-04-29 18:16 UTC, merged