Remove weird figure
SSWConsulting/SSW.Rules.Content pull request #3104
Opened 2022-05-05 23:26 UTC by tkapa

This PR updates the rule https://www.ssw.com.au/rules/do-you-understand-a-data-type-change-data-motion-scripts.

Issue:
	- At first glance, this image is not relevant to the rule.
	- The reader **must** have prior knowledge of who this person is to understand the reference.
	- Even if the reader does understand the trials this person has been through, it still doesn't seem relevant to this rule.

Suggestion:
	1. Remove the image and figure entirely.
	2. Optional - Replace the image with a nice quip about how companies want to stay up to date with their users.

2022-05-06 00:19 UTC, adamcogan requested changes
Tyler as per our conversation I am happy to replace with a better example, but I don't want to remove. I think the image is relevant as this was the first non-binary famous athlete, who made it clear to database developers that a data-type that allowed only 2 options was not enough.
-a

2022-05-06 00:56 UTC, tkapa commented
Hi Adam,
Cc: @jaydenalchin 

With Jayden's assistance I've found a replacement image that might be suitable.

1. Please provide feedback and or approve the image and caption below

![sharon-mccutcheon-IDxuUey3M5E-unsplash](https://user-images.githubusercontent.com/17246482/167049443-e895c5fa-444c-4b09-aeb9-7dbee1caceb3.jpg)
_**Figure: The LGTBQ+ community has taught us a lot about gender identities and the correct data type for gender**_

-t

2022-05-16 01:41 UTC, UlyssesMaclaren approved these changes

2022-06-01 16:22 UTC, tiagov8 commented
Hey @adamcogan this one has been pending for a while... guess waiting for you?

2022-06-17 00:13 UTC, closed without merging