Update Rule “record-a-quick-and-dirty-done-video/rule”
SSWConsulting/SSW.Rules.Content pull request #3560
Opened 2022-07-01 07:27 UTC by jontygardner

Automatically generated by Netlify CMS

2022-07-01 20:08 UTC, adamcogan requested changes
@jontygardner too much is lost... and not generic 
-a

2022-07-05 00:06 UTC, pierssinclairssw commented on rules/record-a-quick-and-dirty-done-video/rule.md
> +* Remote recordings: [Zoom](https://zoom.us/), or [Microsoft Teams](https://www.microsoft.com/en-au/microsoft-teams) via [NDI,](https://www.ndi.tv/) [StreamYard](https://streamyard.com/) (advanced)
the word "or" is very confusing here

2022-07-05 03:09 UTC, jontygardner commented on rules/record-a-quick-and-dirty-done-video/rule.md
> +* Remote recordings: [Zoom](https://zoom.us/), or [Microsoft Teams](https://www.microsoft.com/en-au/microsoft-teams) via [NDI,](https://www.ndi.tv/) [StreamYard](https://streamyard.com/) (advanced)
Done - removed "or"

2022-08-01 03:09 UTC, pierssinclairssw approved these changes

2022-08-30 01:24 UTC, drwharris approved these changes

2022-09-15 19:29 UTC, tiagov8 commented
Hey @jontygardner (editor) / @adamcogan (reviewer)

This PR is here for a while... do you need help getting it done?

2023-01-15 22:41 UTC, merged