Create Rule “avoid-unnecessary-css-classes/rule”
SSWConsulting/SSW.Rules.Content pull request #3717
Opened 2022-07-28 07:21 UTC by Geordie88

Automatically generated by Netlify CMS

2022-07-31 22:28 UTC, bradystroud submitted a review, later dismissed

2022-08-01 20:26 UTC, tiagov8 commented
Hey @Geordie88 

I think I asked you to add me as the reviewer of this one... 

I have dismissed Brady approval since there are changes to be made

2022-08-01 20:27 UTC, tiagov8 commented on rules/avoid-unnecessary-css-classes/rule.md
> +title: Do You Avoid Unnecessary CSS Classes
1. We don't capitalize rules' titles, please fix
2. Missing "?" a the end

2022-08-01 20:29 UTC, tiagov8 commented on rules/avoid-unnecessary-css-classes/rule.md
> +![Figure: Bad Example - The View-All-Link class unessessary as the arrow next class already exists](unessessary-class.jpg)
1. Please fix grammar

2022-08-01 20:30 UTC, tiagov8 commented on rules/avoid-unnecessary-css-classes/rule.md
> +![Figure: Good Example - Instead the arrow next with an additional modifier was used](good-css-class.jpg)
1. Change from `arrow next` to `"arrow-next"` 
2. Check for other occurances

2022-08-01 20:30 UTC, tiagov8 commented on rules/avoid-unnecessary-css-classes/rule.md
> + It can be tempting to add classes on elements, it is often the most obvious solution to CSS problems but doing so will lead to overly cluttered code and a host of overly specific solutions. When wor
1. Remove extra space at the beginning

2022-08-02 23:01 UTC, tiagov8 commented on rules/avoid-unnecessary-css-classes/rule.md
> +![Figure: Bad Example - The View-All-Link class is unessessary, the arrow-next class already exists](unessessary-class.jpg)
Hey @Geordie88 

1. Fix grammar mistake
2. Put all classes name in quotes, so the class name is not confused with the rest of the text   
   e.g. The "View-All-Link" class is... the "arrow-text" class is...

2022-08-03 18:49 UTC, tiagov8 commented on rules/avoid-unnecessary-css-classes/rule.md
> +![Figure: Bad Example - The "View-All-Link" class is unessessary because the "arrow-next" class already exists](unessessary-class.jpg)
1. Fix "unecessary"

2022-08-03 18:51 UTC, tiagov8 requested changes
Hey @Geordie88 

as per https://youtu.be/mdoxkF0s0mo your good example is not correct.

1. Please fix by explaining you should reuse classes instead of creating new ones
**Tip:** Instead of images, you can use code in Markdown (easier to maintain)

PS. If you go further, the "arrow-next" class shouldn't have been created by whoever it was. So don't use it as an example

2022-08-09 00:00 UTC, tiagov8 approved these changes

2022-08-09 00:05 UTC, merged