Create Rule “the-best-learning-resources-for-graphql/rule”
SSWConsulting/SSW.Rules.Content pull request #3855
Opened 2022-08-15 08:34 UTC by AttackOnMorty

Automatically generated by Netlify CMS

2022-08-15 13:05 UTC, adamcogan requested changes
Heya @AttackOnMorty 
1. Is the redirects section correct? Weird that it's linking to angular.
2. What triggered you writing this rule?
-a

2022-08-15 21:06 UTC, matt-goldman approved these changes
Looks ok to me

2022-08-16 01:41 UTC, AttackOnMorty commented
Hi @adamcogan,

> 1. Is the redirects section correct? Weird that it's linking to angular.

No, it's not. I fixed it now.

> 2. What triggered you writing this rule?

I'm addressing an ancient email from you (Subject: Rules to Better Web API - GraphQL #1)

-Luke M

2022-08-16 20:21 UTC, adamcogan approved these changes

2022-08-16 20:21 UTC, merged