Update Rule “do-you-measure-the-effectiveness-of-your-marketing-efforts/rule”
SSWConsulting/SSW.Rules.Content pull request #3872
Opened 2022-08-16 18:42 UTC by camillars

Automatically generated by Netlify CMS

2022-08-16 19:55 UTC, adamcogan requested changes
@camillars 
Avoid the word' our'. Use 3rd person, just like Wikipedia 
-a

2022-08-17 01:42 UTC, UlyssesMaclaren approved these changes

2022-08-17 02:04 UTC, camillars commented
> @camillars Avoid the word' our'. Use 3rd person, just like Wikipedia -a

done

2022-08-18 10:44 UTC, bradystroud approved these changes

2022-08-18 18:24 UTC, adamcogan approved these changes

2022-08-18 18:24 UTC, merged