Create Rule “do-you-use-emoji-in-dynamics-label/rule”
SSWConsulting/SSW.Rules.Content pull request #4249
Opened 2022-10-28 03:39 UTC by zl24622

Automatically generated by Netlify CMS

2022-10-29 12:14 UTC, calumjs requested changes
Just fix a couple of minor typos then good to go

2022-10-29 12:14 UTC, calumjs commented on rules/do-you-use-emoji-in-dynamics-label/rule.md
> +* Not obvious to see - user normally doesn't aware to hover to the label to see the note.
```suggestion
* Not obvious to see - users are often unaware they can hover on the label to see the note.
```

2022-10-29 12:14 UTC, calumjs commented on rules/do-you-use-emoji-in-dynamics-label/rule.md
> +Add a emoji in the label to remind people to hover to see the tooltip.
```suggestion
Add an emoji in the label to remind people to hover to see the tooltip. 
```

2022-10-29 12:14 UTC, calumjs commented on rules/do-you-use-emoji-in-dynamics-label/rule.md
> +![Figure: Add a emoji on the label to remind to people it's a tooltip ](screenshot-at-oct-28-11-29-40.png "Figure: Add a emoji on the label to remind to people it's a tooltip ")
```suggestion
![Figure: Add an emoji on the label to remind to people it's a tooltip ](screenshot-at-oct-28-11-29-40.png "Figure: Add a emoji on the label to remind to people it's a tooltip ")
```

2022-10-29 12:14 UTC, calumjs commented on rules/do-you-use-emoji-in-dynamics-label/rule.md
> +* Flexibility - allow to customize any style or behaviour.
```suggestion
* Flexibility - can customize any style or behaviour.
```

2022-11-14 09:24 UTC, zl24622 reviewed
approved

2022-11-30 22:28 UTC, UlyssesMaclaren approved these changes

2022-12-03 20:15 UTC, adamcogan approved these changes

2022-12-16 01:28 UTC, bradystroud commented
@calumjs this one is blocked by you
Please re-review

2022-12-16 01:30 UTC, calumjs approved these changes

2022-12-16 01:30 UTC, merged

2022-12-16 01:31 UTC, calumjs commented
🚢