Add context to title
SSWConsulting/SSW.Rules.Content pull request #4484
Opened 2022-12-01 21:38 UTC by bradystroud

This rule was show up as "Do you know the best way to get started?" on google 
I didn't know what it was about

2022-12-02 06:23 UTC, wicksipedia requested changes
alternate way to add context

2022-12-02 06:23 UTC, wicksipedia commented on rules/clean-architecture-the-best-way-to-get-started/rule.md
> +title: Do you know the best way to get started with Clean Architecture?
```suggestion
title: Clean Architecture - Do you know the best way to get started?
```

2022-12-03 05:25 UTC, adamcogan approved these changes

2022-12-07 01:48 UTC, wicksipedia commented
can we resolve the outstanding comment first?
not sure why @adamcogan approved it without adding his 2c on that

2022-12-07 05:41 UTC, adamcogan commented
CC @pierssinclairssw 
I prefer the prefix "Clean Architecture -" 
As per https://www.ssw.com.au/rules/prefixes

2022-12-07 05:43 UTC, wicksipedia commented
Committed Adam's preferred way

2022-12-07 05:49 UTC, bradystroud commented
Thanks @wicksipedia - I still need your approval to merge 🙃

2022-12-07 05:50 UTC, wicksipedia approved these changes

2022-12-07 05:50 UTC, merged