fixed link - geo-redundant rule
SSWConsulting/SSW.Rules.Content pull request #4494
Opened 2022-12-02 02:15 UTC by tiagov8

2022-12-02 06:20 UTC, tkapa requested changes
Looks good, just a typo on the rule

2022-12-02 06:20 UTC, tkapa commented on rules/do-you-know-when-to-use-geo-redundant-storage/rule.md
>  * The default when you create it storage accounts.
```suggestion
* The default when you create storage accounts.
```

2022-12-03 05:22 UTC, adamcogan approved these changes

2022-12-07 01:31 UTC, bradystroud approved these changes

2022-12-07 06:46 UTC, tkapa approved these changes

2022-12-07 06:46 UTC, merged