Create Rule “team-works-in-vertical-slices/rule”
SSWConsulting/SSW.Rules.Content pull request #5059
Opened 2023-02-23 04:38 UTC by JackDevAU

Automatically generated by Netlify CMS

2023-02-27 02:08 UTC, bradystroud requested changes

2023-02-27 02:08 UTC, bradystroud commented on rules/team-works-in-vertical-slices/rule.md
> +  - title: Jack Pettit
```suggestion
authors:
  - title: Adam Cogan
    url: https://ssw.com.au/people/adam-cogan
  - title: Jack Pettit
    url: https://ssw.com.au/people/jack-petit
```

2023-02-27 02:08 UTC, bradystroud commented on rules/team-works-in-vertical-slices/rule.md
> +uri: team-works-in-vertical-slices
```suggestion
uri: work-in-vertical-slices
```
If you agree, also update the folder name

2023-02-27 02:08 UTC, bradystroud commented on rules/team-works-in-vertical-slices/rule.md
> +![Figure: Vertical slicing is just like a slice of cake!](vertical-slicing-new-post-img-min.webp)
Stick to png or jpg. Gatsby does fancy image perf optimisation stuff and prefers png or jpg.

2023-02-27 02:08 UTC, bradystroud commented on rules/team-works-in-vertical-slices/rule.md
> +That doesn't help get your weaker skills stronger. Lets look at another way to increase your weaker skills.
```suggestion
That doesn't help get your weak skills stronger. Lets look at another way to strengthen your weaker skills.
```

2023-02-27 02:57 UTC, Hona commented on rules/team-works-in-vertical-slices/rule.md
> +4. Asking questions
I'd add a point to this that while a vertical slice is great for someone to get across the project - you need to spread the IP knowledge across the team, as losing someone becomes an increased risk

2023-02-27 23:45 UTC, tiagov8 commented
Hey @JackDevAU 

1. Please add this rule to a category 

PS. You should use the same PR. Ping me on Teams if unsure

FYI - I have made a bunch of updates to improve the rule reading. The most important one is that we don't use "At SSW, we..." on Rules. Rules should be generic for anyone to follow ;)

2023-02-27 23:53 UTC, JackDevAU commented
>     1. Please add this rule to a category

Done - Add to rules to better Scrum

2023-02-27 23:54 UTC, tiagov8 approved these changes

2023-02-28 05:23 UTC, bradystroud approved these changes

2023-02-28 05:23 UTC, merged