🔗 Refer to MS learn instructions
SSWConsulting/SSW.Rules.Content pull request #5210
Opened 2023-03-16 23:18 UTC by bradystroud

- 🔧 Less maintenance needed on this rule - MS will keep their docs up to date
- 🧼 Shorter, cleaner rule

https://learn.microsoft.com/en-us/connectors/custom-connectors/port-tunneling

2023-03-16 23:32 UTC, SamBWagner commented on rules/port-forwarding/rule.md
>  ## Dev Tunnels Setup
It feels like we're not just sending them to the docs but rather deleting the whole section. Either keep all or lose all

2023-03-16 23:33 UTC, SamBWagner requested changes
Left comments to address :) Feels like we're deleting a lot.

2023-03-16 23:57 UTC, SamBWagner approved these changes
🚢
Checked by Bryden

2023-03-17 01:17 UTC, danielmackay requested changes
I like the idea of leveraging the MS learn docs, however I feel the step outlined in the rule are a lot more streamlined compared to MS learn (which covers APIM and Power Platform, but also less details about the core use case).

My preference would be to leave the screenshots and instructions in the rule.

2023-03-17 03:23 UTC, SamBWagner commented
I believe the sentiment was that providing a guide, if it's already in the docs, is now a maintenance cost.

2023-03-20 10:01 UTC, adamcogan commented
Hey @danielmackay @bradystroud @SamBWagner @lukecookssw @pierssinclairssw 

I agree that in general SSW Rules should not create content that exists elsewhere eg. docs.microsoft.com

However in this case:
A: the Rule is clearer and shorter than the reference docs.

B: this is a new feature and so this SSW Rule may end up getting more links from other sites, since it is simpler to read.

C: the Rule is already created and at this stage it is not out-of-date. So this would be pre-optimizing to kill the content.

In short, kill the content when it is out-of-date... and the effort to update it is not worth it.

-a

2023-03-20 21:20 UTC, closed without merging