🔎 Code consistency - Add ensure compliance section
SSWConsulting/SSW.Rules.Content pull request #5420
Opened 2023-04-20 04:19 UTC by bradystroud

2023-04-20 09:39 UTC, adamcogan approved these changes
Love this ⭐️

2023-04-20 10:09 UTC, adamcogan requested changes
Hey Brady
CC @wicksipedia @William-Liebenberg

Love this topic to make our code neater... Let's improve the rule ⭐️ 

1. It is good to use .editorconfig however you want to be doing this from the client side (as warnings), rather than commit and then magic happens via a GitHub Action. Please make this approach the bad example

2. Also this Action looks dead. It has not been touched in 4 years. Mention it is inactive

3. The linting tool used by the action is read-only. It has been archived.

4. That linter tool looks like it only checks white space changes. ESLint and .NET can use the editorconfig file and check for a lot more

-a
www.AdamCogan.com

2023-04-21 00:22 UTC, UlyssesMaclaren approved these changes

2023-04-21 03:33 UTC, bradystroud commented
> 1. It is good to use .editorconfig however you want to be doing this from the client side (as warnings), rather than commit and then magic happens via a GitHub Action. Please make this approach the bad example

Not Done - I think it is still valuable to have this on PRs. Some IDEs (vim) wont format code so the PR gate ensures all code on main is formatted.
I improved the wording to make it sound like an extra step, not a replacement to having it locally.

> 2. Also this Action looks dead. It has not been touched in 4 years. Mention it is inactive
> 3. The linting tool used by the action is read-only. It has been archived.
> 4. That linter tool looks like it only checks white space changes. ESLint and .NET can use the editorconfig file and check for a lot more

I removed the link to this action

2023-04-28 01:34 UTC, UlyssesMaclaren approved these changes

2023-04-29 14:20 UTC, adamcogan approved these changes

2023-04-29 14:20 UTC, merged

2023-05-07 07:20 UTC, william-liebenberg commented on rules/consistent-code-style/rule.md
Hi Brady

Your instructions are a bit on the skinny side. I'd like to see more about how to configure a good coding style and preserve it via .editorConfig and then sharing it with the team for consistency.

e.g 

To add an editor config, you can use:
- VS2022 to add a new `.editorConfig` with some of the .NET defaults as you described already
- Dotnet CLI (same defaults). 

In VS2022 you can configure your code style by going to Tools | Options | Text Editor | C# | Code Style 
From here you can generate a .editorConfig as well with all the custom VS rules that aren't part of the regular .editorConfig spec and still share them with the team.

![image](https://user-images.githubusercontent.com/23464439/236663697-f798905d-c5ac-4035-bf88-1e7642e756be.png)


I'd also note that you can use `dotnet format` to apply all the whitespace, code style and code analysis changes to the project. Or you can  run them separately as:

- `dotnet format whitespace`
- `dotnet format style`
- `dotnet format analyzers`