Update Rule “use-branch-protection/rule”
SSWConsulting/SSW.Rules.Content pull request #5432
Opened 2023-04-23 21:44 UTC by BrookJeynes

Automatically generated by Netlify CMS

2023-04-28 00:27 UTC, bradystroud approved these changes
Hey @BrookJeynes 
this is screenshot of a private repo. 

- [x] Can you confirm with @pierssinclairssw this is not an issue?

I think its fine here but in future try stick to stuff that's already public 🙂

2023-04-28 00:30 UTC, bradystroud requested changes
Sorry I meant to request changes 🙃

2023-05-07 23:23 UTC, pierssinclairssw approved these changes

2023-05-07 23:23 UTC, BrookJeynes commented
> Hey @BrookJeynes this is screenshot of a private repo.
> 
>     * [x]  Can you confirm with @pierssinclairssw this is not an issue?
> 
> 
> I think its fine here but in future try stick to stuff that's already public 🙂

As per my Teams conversation with @pierssinclairssw, he said it's fine

2023-05-07 23:24 UTC, bradystroud approved these changes

2023-05-07 23:24 UTC, merged