Created script to detect unused images
SSWConsulting/SSW.Rules.Content pull request #5782
Opened 2023-06-13 04:42 UTC by BrookJeynes

- Created script to detect unused images
- Created github action to use script on PR

![image](https://github.com/SSWConsulting/SSW.Rules.Content/assets/25432120/d915a979-565e-4d06-ac85-bc4fff9309cd)
**Figure: GitHub Action output**

2023-06-13 07:01 UTC, bradystroud requested changes
Looking good 🛶

2023-06-13 15:30 UTC, tiagov8 commented
Hey @BrookJeynes / @bradystroud 

Should we have a label for these PRs that aren't content edits?

2023-06-14 03:21 UTC, bradystroud commented
@tiagov8 @BrookJeynes 
> Should we have a label for these PRs that aren't content edits?

Good idea - done

2023-06-19 00:57 UTC, bradystroud requested changes

2023-06-19 00:57 UTC, bradystroud commented on .github/workflows/check-images.yml
> +
Its not clear what this does and what the result is used for

2023-06-19 04:27 UTC, bradystroud approved these changes
LGTM

2023-06-19 04:30 UTC, merged