✨ Add rule to favicon optimisation
SSWConsulting/SSW.Rules.Content pull request #6183
Opened 2023-07-28 06:27 UTC by jackreimers

2023-07-28 23:19 UTC, bradystroud requested changes

2023-07-28 23:19 UTC, bradystroud commented on rules/optimise-your-favicon/rule.md
> +- Windows and Mac Icons
condense this section to a sentence

2023-07-28 23:19 UTC, bradystroud commented on rules/optimise-your-favicon/rule.md
> +Favicons are commonplace in web development, but did you know your favicon may not be properly optimised for all devices?
I prefer answering the question (rule title) in the intro, and then going into more detail after

2023-08-01 00:21 UTC, UlyssesMaclaren approved these changes

2023-08-01 06:05 UTC, Hona requested changes
screenshots I would 150% zoom & exclude random browser UI

2023-08-04 06:24 UTC, jaydenalchin approved these changes

2023-08-07 05:30 UTC, bradystroud commented
The images you want to use haven't been added

2023-08-07 05:52 UTC, bradystroud commented
> The images you want to use haven't been uploaded

Fixed

2023-08-07 06:00 UTC, bradystroud requested changes

2023-08-07 06:17 UTC, bradystroud approved these changes

2023-08-07 06:26 UTC, Hona approved these changes

2023-08-07 06:26 UTC, merged