Internal work category - add to a top category
SSWConsulting/SSW.Rules.Content pull request #6278
Opened 2023-08-09 22:50 UTC by bradystroud

2023-08-10 06:59 UTC, jaydenalchin requested changes
@bradystroud as per our conversation we should consider un-making this new category instead, seems a lot of redundancy with [Rules to better daily ops](https://www.ssw.com.au/rules/rules-to-better-daily-office-operations-dailyops/ )

2023-08-10 10:49 UTC, adamcogan approved these changes

2023-08-16 23:07 UTC, jaydenalchin approved these changes

2023-08-17 01:37 UTC, UlyssesMaclaren approved these changes

2023-08-17 01:37 UTC, merged