Create a new category called '.NET Migrations' and move all related migration rules into it
SSWConsulting/SSW.Rules.Content pull request #6580
Opened 2023-09-05 07:53 UTC by YazhiChen

Create a new category called '.NET Migrations' and move all related migration rules into it

2023-09-06 21:27 UTC, bradystroud requested changes

2023-09-06 21:27 UTC, bradystroud commented on categories/net-migrations/index.md
@lukecookssw @YazhiChen 

I dont think we need a new top category for this, it falls under software development.

If we did have a top category, maybe it should be for Migrations in general (not limited to .NET)

1. Delete it if you agree

2023-09-08 01:31 UTC, tiagov8 commented on categories/net-migrations/index.md
+1 top categories should be kept lean

2023-09-08 01:34 UTC, YazhiChen commented on categories/net-migrations/index.md
This is required by @adamcogan to create a separate .NET Migration category. 
But detailed category still need to be reviewed and discussed with @lukecookssw

2023-09-08 01:59 UTC, tiagov8 commented on categories/net-migrations/index.md
Hi @YazhiChen , 

as per our conversation on Teams, the requirement is for a new category, not a new top category.

1. Please revert the new top category
2. Add a new **Rules to Better .NET Migrations** (no version to be added here, keep it generic) under "Software Development"

2023-09-08 15:44 UTC, tiagov8 commented on categories/net-migrations/index.md
Hi @YazhiChen 

As per my conversation with @lukecookssw 

I removed the part to not have version numbers. Please include them in your category titles so we can filter different migrations

2023-09-11 22:07 UTC, tiagov8 submitted a review, later dismissed
1. Please action my comment https://github.com/SSWConsulting/SSW.Rules.Content/pull/6580#discussion_r1320033153

2023-09-12 08:02 UTC, YazhiChen commented on categories/net-migrations/index.md
Done. @tiagov8  @lukecookssw

2023-09-12 20:19 UTC, bradystroud approved these changes
LGTM

2023-09-12 23:31 UTC, merged