Added the word "Issues" and moved email subject to its own rule "mean…
SSWConsulting/SSW.Rules.Content pull request #6613
Opened 2023-09-06 16:49 UTC by tiagov8

…ingful-pbi-titles"

Exisitng email subject rule: https://www.ssw.com.au/rules/good-email-subject/

2023-09-06 21:35 UTC, bradystroud requested changes

2023-09-06 21:35 UTC, bradystroud commented on rules/meaningful-pbi-titles/rule.md
> +So what separates a **good** PBI/Issue title from a **bad** one?
PBI is a Scrum term, not specific to DevOps. GitHub issues are a form of a PBI.
Typically I'll use the term PBI to cover any form of PBI (DevOps, Trello, GitHub - Any backlog item)

1. Action if you agree

2023-09-06 22:23 UTC, UlyssesMaclaren approved these changes

2023-09-07 01:50 UTC, bradystroud approved these changes

2023-09-07 01:50 UTC, merged