split migration rule into two
SSWConsulting/SSW.Rules.Content pull request #6669
Opened 2023-09-12 03:07 UTC by lukecookssw

This PR creates two rules which will supercede the "Do you know how to handle complex .NET migrations?" rule:

- Do you create a migration plan?
- Migrating Web Apps to .NET Core

I **have not** added these rules to a category yet, as we are waiting on #6580 to be merged so we have the appropriate category to link these rules under. I'm happy for these rules to be "orphaned" for now, but let me know if that's a problem.

2023-09-12 03:31 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +Migrating from .NET Framework to .NET Core brings huge advantages to your app's performance, hosting fees, and maintainability. But it's important that you understand what the road to .NET Core looks
```suggestion
Migrating from .NET Framework (4.x) to the latest .NET (5+) brings huge advantages to your app's performance, hosting fees, and maintainability. But it's important that you understand what the road to .NET 5+ looks like for your app *before* you start breaking things! So how do you ensure your migration is being done the right way? 
```

2023-09-12 03:33 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +The migration from .NET Framework to .NET Core is the perfect opportunity for you to take stock of your current application architecture, and address any technical debt your app has accumulated. Tryi
```suggestion
The migration to a newer versions of .NET is the perfect opportunity for you to take stock of your current application architecture, and address any technical debt your app has accumulated. Trying to migrate an application that's poorly architected or carrying a lot of tech debt will make your migration **exponentially harder**. Therefore, now is the time to perform a full audit of your app and ensure you have PBIs to rectify these problems before you consider it "migration-ready".
```

2023-09-12 03:34 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +If your app has 3rd party dependencies (e.g. with a financial system, reporting system, etc.) - now is the time to do some investigation around those integration points to determine whether those ser
```suggestion
If your app has 3rd party dependencies (e.g. with a financial system, reporting system, etc.) - now is the time to do some investigation around those integration points to determine whether those services provide compatible libraries and how those libraries differ (if at all). Create PBIs for these as well. 
```

2023-09-12 03:38 UTC, wicksipedia reviewed
.NET Core ended with 3.1

Since v5 - it is all just .NET now (and I got tired of fixing the Core references)

2023-09-12 03:38 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +If you host your app on premise, it's also worth checking your infrastructure to ensure it's got the necessary .NET Core runtimes.
```suggestion
If you host your app on premise, it's also worth checking your infrastructure to ensure it's has the necessary runtimes.
```

2023-09-12 03:38 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +### Change all your projects to be able to target multiple Target framework monikers (TFM)
```suggestion
### Change all your projects to be able to target multiple Target Framework Monikers (TFM)
```

2023-09-12 03:38 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +Targeting both your current .NET Framework version *and* your future .NET Core version will give you the following information:
```suggestion
Targeting both your current .NET Framework version *and* your future .NET version will give you the following information:
```

2023-09-12 03:38 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +* Expose any build errors you receive when trying to build for .NET Core
```suggestion
* Expose any build errors you receive when trying to build for .NET
```

2023-09-12 03:38 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +Imagine you *don't* do this, and instead, you simply target .NET Core. You get a list of 100 build errors due to breaking changes - too many for 1 Sprint (or 2 Sprints, or 3).
```suggestion
Imagine you *don't* do this, and instead, you simply target there newer version of .NET. You get a list of 100 build errors due to breaking changes - too many for 1 Sprint (or 2 Sprints, or 3).
```

2023-09-12 03:38 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +Then you're told there's an urgent bug/feature/whatever that needs fixing ASAP. But you've still got 50 build errors when you're targeting .NET Core.
```suggestion
Then you're told there's an urgent bug/feature/whatever that needs fixing ASAP. But you've still got 50 build errors when you're targeting .NET.
```

2023-09-12 03:38 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +While you were fixing those .NET Core build errors, you wrote code that isn't compatible with .NET Framework. Now you have an urgent bug/feature/whatever, as well as 25 new build errors you have to s
```suggestion
While you were fixing those build errors, you wrote code that isn't compatible with .NET Framework. Now you have an urgent bug/feature/whatever, as well as 25 new build errors you have to solve ☠️.
```

2023-09-12 03:38 UTC, wicksipedia commented on rules/do-you-create-a-migration-plan/rule.md
> +Using multiple TFMs from day 1 ensures you are fixing the breaking changes for .NET Core, *without* introducing breaking changes in .NET Framework.
```suggestion
Using multiple TFMs from day 1 ensures you are fixing the breaking changes for .NET, *without* introducing breaking changes in .NET Framework.
```

2023-09-12 04:50 UTC, GordonBeeming commented on rules/do-you-create-a-migration-plan/rule.md
> +If you host your app on premise, it's also worth checking your infrastructure to ensure it's has the necessary runtimes.
```suggestion
If you host your app on premise, it's also worth checking your infrastructure to ensure it has the necessary runtimes.
```

2023-09-12 04:53 UTC, GordonBeeming commented on rules/do-you-create-a-migration-plan/rule.md
> +Imagine you *don't* do this, and instead, you simply target there newer version of .NET. You get a list of 100 build errors due to breaking changes - too many for 1 Sprint (or 2 Sprints, or 3).
```suggestion
Imagine you *don't* do this, and instead, you simply target the newer version of .NET. You get a list of 100 build errors due to breaking changes - too many for 1 Sprint (or 2 Sprints, or 3).
```

2023-09-13 00:08 UTC, GordonBeeming approved these changes
LGTM 🚢

2023-09-13 00:38 UTC, merged

2023-09-13 00:50 UTC, YazhiChen requested changes
Please update the typo and update the link for the rule - Do you know how to migrate Web.config to ASP.NET Core?

2023-09-13 00:50 UTC, YazhiChen commented on rules/do-you-create-a-migration-plan/rule.md
> +If your app has 3rd party dependencies (e.g. with a financial system, reporting system, etc.) - now is the time to do some investigation around those integration points to determine whether those ser
```suggestion
If your app has 3rd party dependencies (e.g. with a financial system, reporting system, etc.) - now is the time to investigate those integration points to determine whether those services provide compatible libraries and how those libraries differ (if at all). Create PBIs for these as well. 
```

2023-09-13 00:50 UTC, YazhiChen commented on rules/do-you-create-a-migration-plan/rule.md
> +While this guide aims to give you a high-level view of migrating your app, there are other some special considerations when dealing with complex applications and web apps. Check out these othe rules:
```suggestion
While this guide aims to give you a high-level view of migrating your app, there are other some special considerations when dealing with complex applications and web apps. Check out these other rules:
```

2023-09-13 00:50 UTC, YazhiChen commented on rules/do-you-create-a-migration-plan/rule.md
> +  - dotnet-upgrade-assistant
Why are only these two rules listed as related rules here

2023-09-13 00:50 UTC, YazhiChen commented on rules/migrating-web-apps/rule.md
> +- [Do you know how to migrate Web.config to ASP.NET Core?](https://www.ssw.com.au/rules/know-how-to-migrate-owin-to-asp-net-core/)
This is probably the previous mistake.
```suggestion
- [Do you know how to migrate Web.config to ASP.NET Core?](https://ssw.com.au/rules/know-how-to-migrate-web-config-to-asp-net-core/)
```