New rule on avoid common mistakes (collated)
SSWConsulting/SSW.Rules.Content pull request #6912
Opened 2023-10-05 17:47 UTC by tiagov8

as per @jaydenalchin 's **Re: SSW.Rules - Create new "Content Design" category + content improvements**

From:

a.	[https://www.ssw.com.au/rules/do-you-write-the-word-email-in-the-correct-format/](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Frules%2Fdo-you-write-the-word-email-in-the-correct-format%2F&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C7b54d4689d5f4e39813508dbb97b3609%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638307711080764397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y8AqB2SE1jed6hMuOR%2BvbkZwhU17wD2ZuQi5krX%2FIhE%3D&reserved=0) 
b.	[https://www.ssw.com.au/rules/do-you-know-when-to-versus-and-verses/](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Frules%2Fdo-you-know-when-to-versus-and-verses%2F&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C7b54d4689d5f4e39813508dbb97b3609%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638307711080764397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s6pxzqATU6JdSQi60BKKhnwHGG3%2B2pCf8SMmiuJVzSU%3D&reserved=0)
c.	[https://www.ssw.com.au/rules/use-cannot-and-website-instead-of-separated-words/](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Frules%2Fuse-cannot-and-website-instead-of-separated-words%2F&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C7b54d4689d5f4e39813508dbb97b3609%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638307711080764397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vJrsSUXEl97h5fK9FXI9qkAgZQmoA5TDQxowC5EEEok%3D&reserved=0)
d.	[https://www.ssw.com.au/rules/use-username-instead-of-user-name/](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Frules%2Fuse-username-instead-of-user-name%2F&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C7b54d4689d5f4e39813508dbb97b3609%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638307711080764397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5mXGHXqQLkKEuW3WAO75OYXxxemv%2BbTKYvXaGefEAws%3D&reserved=0)
e.	[https://www.ssw.com.au/rules/use-taskbar-instead-of-task-bar/](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Frules%2Fuse-taskbar-instead-of-task-bar%2F&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C7b54d4689d5f4e39813508dbb97b3609%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638307711080764397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fIw1PX0pvf0zfVN7I9GTVgZ5Ae52g8gh0YthDKmOPKc%3D&reserved=0)
f.	[https://www.ssw.com.au/rules/use-setup-and-set-up-correctly/](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Frules%2Fuse-setup-and-set-up-correctly%2F&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C7b54d4689d5f4e39813508dbb97b3609%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638307711080764397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OEW8Es%2FZw0EZd9LfZ39JNW4hZ4qU22oPzmT6S87dpS0%3D&reserved=0)

2023-10-06 00:09 UTC, jaydenalchin requested changes

2023-10-06 00:09 UTC, jaydenalchin commented on rules/avoid-common-mistakes/rule.md
> +### Understand different spellings have different meanings
```suggestion
### Syntax changes the meaning of certain words
```

2023-10-06 15:48 UTC, tiagov8 commented on rules/avoid-common-mistakes/rule.md
> +* **“Versus”** refers to 2 or more parties in opposition to one another, especially in sports or legal situations (e.g. "Floyd verses Mayweather")
OMG! Thanks, @jaydenalchin

2023-10-08 21:14 UTC, jaydenalchin approved these changes

2023-10-08 22:50 UTC, bradystroud commented
Hey @tiagov8 @jaydenalchin 

Ignore the failing check for now

hey @Aibono1225 

Please investigate why it failed (I think you already fixed it and this branch is old 🙂)

2023-10-08 22:58 UTC, merged