Updated outdatd image
SSWConsulting/SSW.Rules.Content pull request #7138
Opened 2023-10-31 06:45 UTC by ozairashfaqueSSW

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

Email: SSW Rules - improving rules :
•	The rule “Login Security - Do you know the appropriate error message for an invalid username or password entry?” has a outdated screenshot and it need to be replaced. See:
[https://www.ssw.com.au/rules/login-security-do-you-know-the-correct-error-message-for-an-incorrect-user-name-or-password/](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Frules%2Flogin-security-do-you-know-the-correct-error-message-for-an-incorrect-user-name-or-password%2F&data=05%7C01%7COzairAshfaque%40ssw.com.au%7C40bcb50c648a489fd8b908dbd99d075b%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638343040685183081%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S3Yypl%2BRporxuCSdQT7ecFDFO2PXwfHzIuoA6j2pqjA%3D&reserved=0)

> 2. What was changed?

- Updated outdated image

> 3. Did you do pair or mob programming?

- I had discussion with @adamcogan and screenshot in the rule is outdated.

2023-11-01 15:30 UTC, tiagov8 submitted a review, later dismissed

2023-11-01 15:32 UTC, tiagov8 requested changes
Hi @ozairashfaqueSSW 

I see the new image path, but not the new image uploaded...

- [ ] 1. Please include the image upload in your PR (or link to another PR if it's the case)

2023-11-01 22:38 UTC, ozairashfaqueSSW commented
> Hi @ozairashfaqueSSW
> 
> I see the new image path, but not the new image uploaded...
> 
> * [x]  1. Please include the image upload in your PR (or link to another PR if it's the case)

I have added image to assets folder and fixed the path

2023-11-02 13:09 UTC, tiagov8 approved these changes

2023-11-02 20:02 UTC, merged

2023-11-03 23:34 UTC, william-liebenberg reviewed
LGTM