Update rule.md
SSWConsulting/SSW.Rules.Content pull request #7324
Opened 2023-11-27 05:54 UTC by synnoveisabel

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

Sugar Learning item [make-a-small-content-change-to-ssw-rules](https://my.sugarlearning.com/SSW/items/13091/make-a-small-content-change-to-ssw-rules-check-in-publish) 

> 2. What was changed?
* Typo in "brainstorming day retro rule"
* "Good"- and "bad" container around figure text in "do you return a resource url rule"

2023-11-27 10:51 UTC, bradystroud requested changes
Looks good Isabel 🙂

Can you please update the PR title to be more informative?
as per https://www.ssw.com.au/rules/write-a-good-pull-request/#1-write-a-concise-and-self-explanatory-title

2023-11-27 21:20 UTC, tiagov8 approved these changes

2023-11-27 22:21 UTC, UlyssesMaclaren approved these changes

2023-11-28 22:40 UTC, bradystroud approved these changes

2023-11-28 22:40 UTC, merged