Create Rule “rules-to-better-automation/rule”
SSWConsulting/SSW.Rules.Content pull request #7471
Opened 2023-12-07 05:42 UTC by JackDuan123

**Tip: Use [SSW Rule Writer GPT](https://chat.openai.com/g/g-cOvrRzEnU-ssw-rules-writer) for help with writing rules 🤖**
>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

✏️ My random chat with seth

> 2. What was changed?

✏️ Adding a rule called rules to better automation

> 3. Did you do pair or mob programming (list names)?

✏️ No

2023-12-07 07:04 UTC, danielmackay requested changes
In general, this rule does not seem super clear to me.  I'd like to see a much clearer description of what the problem is and how your rule solves that.

2023-12-11 02:10 UTC, sethdailyssw commented on rules/rules-to-better-automation/rule.md
> +A social group's success often depends on its conventions—shared norms and agreements that guide communication, decision-making, and unity. Strong conventions help navigate challenges, resolve confli
We do this all the time - we introduce automation that changes the way people work in the short term but gives efficiency benefits in the long term once people adjust.

If you want to make this rule you need to define 'convention' and at which points it's acceptable and unacceptable to break conventions.

It needs to be specific i.e. make it 'followable'

2023-12-11 02:11 UTC, sethdailyssw requested changes
We do this all the time - we introduce automation that changes the way people work in the short term but gives efficiency benefits in the long term once people adjust.

If you want to make this rule you need to define 'convention' and at which points it's acceptable and unacceptable to break conventions.

It needs to be specific i.e. make it 'followable'

2024-01-29 22:52 UTC, sethdaily requested changes
@JackDuan123 I don't think this rule is clear or specific

1. Improve it, or delete the branch

2024-02-09 10:47 UTC, danielmackay commented
Closing this pull request due to lack of activity.  

@JackDuan123 - if this is is a change you really want to make, please update your branch and create another PR.

2024-02-09 10:47 UTC, closed without merging