Added missing ? + fixed syntaxes
SSWConsulting/SSW.Rules.Content pull request #7602
Opened 2023-12-19 12:18 UTC by tiagov8

cc @danielmackay 

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

found myself

> 2. What was changed?

Added missing ? + fixed syntaxes

> 3. Did you do pair or mob programming (list names)?

no

2023-12-19 12:35 UTC, BrookJeynes approved these changes

2023-12-19 21:54 UTC, danielmackay requested changes
1 comment

2023-12-19 21:54 UTC, danielmackay commented on rules/use-code-migrations/rule.md
> -    ```bash
Can you revert the indentation on these code blocks (same with the other code blocks)?  Change this to 2 spaces breaks markdown linting

![image](https://github.com/SSWConsulting/SSW.Rules.Content/assets/2636640/e7e70a11-4682-4402-a097-780326a351d5)
**Figure: Warning caused by incorrect indentation**

2023-12-21 12:26 UTC, camillars approved these changes

2023-12-21 12:30 UTC, merged