Update Rule “groups-in-microsoft-365/rule”
SSWConsulting/SSW.Rules.Content pull request #7819
Opened 2024-01-23 04:31 UTC by lloydcollinsssw

Automatically generated by Decap CMS

2024-01-23 17:19 UTC, tiagov8 requested changes

2024-01-23 17:19 UTC, tiagov8 commented on rules/groups-in-microsoft-365/rule.md
> +**NOTE**
Hi @lloydcollinsssw 

We want to keep things consistent...

- [ ] 1. Please change to `**Note:** {{ TEXT }}`

2024-01-23 17:19 UTC, tiagov8 commented on rules/groups-in-microsoft-365/rule.md
> +NOTE Shared mailbox
- [ ] 2. Please change to `**Note:** {{ TEXT }}`

2024-01-28 23:58 UTC, closed without merging

2024-01-28 23:59 UTC, lloydcollinsssw commented
Start again I was thinking this was sugarlearning and I could keep revising the page. save and take a look again at what I had writtten