New Rule - Do you know how to allocate the expenses to the offices?
SSWConsulting/SSW.Rules.Content pull request #7832
Opened 2024-01-24 23:54 UTC by JimmyChenSSW

**Tip: Use [SSW Rule Writer GPT](https://chat.openai.com/g/g-cOvrRzEnU-ssw-rules-writer) for help with writing rules 🤖**
>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

A task from @stephanfakossw that create a rule to explain how we allocate expenses to different offices.

> 2. What was changed?

- New rule created
- Update the category of better accounting

> 3. Did you do pair or mob programming (list names)?

@stephanfakossw

2024-01-25 00:00 UTC, sethdaily commented on rules/allocate-the-expenses-to-the-offices/rule.md
> +![](Allocate-expense-1.jpg)
Add a caption

2024-01-25 00:02 UTC, sethdaily commented on rules/allocate-the-expenses-to-the-offices/rule.md
> +* If Bob travels from Sydney to Melbourne for training, then the cost is allocated to Sydney.
```suggestion
::: greybox
* If Bob travels from Sydney to Brisbane to give a speech at a conference held by the Brisbane office, the cost should be allocated to Brisbane.
* If Bob travels from Sydney to Melbourne for training, then the cost is allocated to Sydney.
:::

::: good
Figure: Good example - always allocate expenses to the more relevant office
:::
```

2024-01-25 00:04 UTC, sethdaily commented on rules/allocate-the-expenses-to-the-offices/rule.md
> +![✅ Good Example: Software expenses from the company level would be assigned to different offices based on the admin rate](keep-yourself-connected-3.png)
```suggestion
::: good
![Figure: Good example - Software expenses from the company level would be assigned to different offices based on the admin rate](keep-yourself-connected-3.png)
:::
```

2024-01-25 00:07 UTC, sethdaily commented on rules/allocate-the-expenses-to-the-offices/rule.md
> +Any errors or inconsistencies discovered during the review should be identified and promptly corrected.
I don't think this is necessary - obvious
```suggestion
```

2024-01-25 00:07 UTC, sethdaily commented on rules/allocate-the-expenses-to-the-offices/rule.md
> +This communication is essential to ensure that everyone is on the same page and understands their role in the process.
I don't think you need these - obvious
```suggestion
```

2024-01-25 00:08 UTC, sethdaily requested changes
1. See comments
2. I would change the title from:
Do you know how to allocate the expenses to the offices?
to
Do you know how to allocate expenses per office?

2024-01-25 02:24 UTC, JimmyChenSSW commented on rules/allocate-the-expenses-to-the-offices/rule.md
> +![](Allocate-expense-1.jpg)
Updated using new figure

2024-01-25 02:33 UTC, JimmyChenSSW reviewed
Changed as per suggested by Seth

2024-01-26 19:34 UTC, tiagov8 approved these changes

2024-01-26 19:36 UTC, merged