✨ New rule - Successful Reachouts
SSWConsulting/SSW.Rules.Content pull request #8038
Opened 2024-03-01 17:05 UTC by bradystroud

**Tip: Use [SSW Rule Writer GPT](https://chat.openai.com/g/g-cOvrRzEnU-ssw-rules-writer) for help with writing rules 🤖**
>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

My big brain
Our reachouts could be more successful, i want to document whats worked for me

2024-03-01 19:43 UTC, tiagov8 requested changes
@bradystroud 

- [ ] 1. Could we add https://www.ssw.com.au/rules/use-emojis/ as related?

2024-03-01 19:43 UTC, tiagov8 commented on rules/successful-reachouts/rule.md
> +Its important to ask the question early in the message, as most people will only glance at the .
Hey @bradystroud 

- [ ] 1. Fix from "Its" to "It's "
- [ ] 2. I think there is a word missing at the end "glance at the ."
- [ ] 3. Remove the full stops from the lists as per https://www.ssw.com.au/rules/avoid-full-stops-in-bullet-point-lists

2024-03-01 19:43 UTC, tiagov8 commented on rules/successful-reachouts/rule.md
> +![Figure: Typical developers LinkedIn inbox](developer-reachout-spam.png)
@bradystroud 

- [ ] 1. Should we make this the "bad" example?
- [ ] 2. Consider making this a medium image... as it's too vertical (causing scrolling) https://ssw.com.au/rules/rule/#6-images

2024-03-01 19:43 UTC, tiagov8 commented on rules/successful-reachouts/rule.md
> +title: Do you know to make your Linkedln reachouts stand out?
@bradystroud 

- [ ] 1. Fix "LinkedIn"
- [ ] 2. I think we can remove the word "your"

2024-03-03 22:55 UTC, sethdaily approved these changes

2024-03-03 22:57 UTC, sethdaily commented on rules/successful-reachouts/rule.md
> +---
```suggestion
related:
- do-you-know-the-main-features-of-linkedin-talent-hub
- when-to-hire-more-people
- do-you-use-linkedin-recruiter-to-help-you-find-more-candidates
---
```

2024-03-03 23:01 UTC, sethdaily commented on rules/successful-reachouts/rule.md
> +---
```suggestion
related:
- do-you-know-the-main-features-of-linkedin-talent-hub
- when-to-hire-more-people
- do-you-use-linkedin-recruiter-to-help-you-find-more-candidates
created: 2024-03-1T01:55:35.941Z
guid: 012a5f87-5cfb-4002-8d5f-4d2a8787ed6a
archivedreason: null
---
```

2024-03-03 23:03 UTC, sethdaily approved these changes

2024-03-03 23:03 UTC, sethdaily commented
@tiagov8 
1. pls approve your requested changes

2024-03-03 23:41 UTC, JackDevAU commented on rules/successful-reachouts/rule.md
> +- do-you-use-linkedin-recruiter-to-help-you-find-more-candidates
```suggestion
  - do-you-know-the-main-features-of-linkedin-talent-hub
  - when-to-hire-more-people
  - do-you-use-linkedin-recruiter-to-help-you-find-more-candidates
```

2024-03-03 23:49 UTC, JackDevAU commented on rules/successful-reachouts/rule.md
> +created: 2024-03-1T01:55:35.941Z
```suggestion
created: 2024-03-01T01:55:35.941Z
```

2024-03-03 23:52 UTC, JackDevAU commented on rules/successful-reachouts/rule.md
> +created: 2024-03-1T01:55:35.941Z
The issue seems to be that the date wasn't 100% valid ISO 8601 format 🙃

2024-03-03 23:53 UTC, JackDevAU approved these changes

2024-03-04 07:12 UTC, merged