New rule - POC and MVP
SSWConsulting/SSW.Rules.Content pull request #8070
Opened 2024-03-06 14:54 UTC by bradystroud

**Tip: Use [SSW Rule Writer GPT](https://chat.openai.com/g/g-cOvrRzEnU-ssw-rules-writer) for help with writing rules 🤖**
>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

Email - RE: SSW Rule - POC vs MVP

> 2. What was changed?

✏️

> 3. Did you do pair or mob programming (list names)?

✏️

2024-03-06 23:26 UTC, jaydenalchin requested changes
@bradystroud great rule but make sure it's added to a category

2024-03-06 23:27 UTC, tiagov8 commented
> @bradystroud great rule but make sure it's added to a category

was about to say the same :)

2024-03-07 00:49 UTC, danielmackay submitted a review, later dismissed
1 minor comment

2024-03-07 00:49 UTC, danielmackay commented on rules/poc-vs-mvp/rule.md
> +title: Do you understand the difference between POC and MVPs?
Either both terms should be singular or plural

```suggestion
title: Do you understand the difference between a POC and MVP?
```

2024-03-07 08:09 UTC, bradystroud commented
@jaydenalchin 
> @bradystroud great rule but make sure it's added to a category

Done - Added a few

2024-03-07 18:30 UTC, tiagov8 requested changes

2024-03-07 18:30 UTC, tiagov8 commented on categories/communication/rules-to-better-communication.md
> +  - poc-vs-mvp
Hey @bradystroud 

Agreed this is important, but I don't think it belongs to "Communication" category

2024-03-07 18:31 UTC, bradystroud commented on categories/communication/rules-to-better-communication.md
> +  - poc-vs-mvp
I agree, removed

2024-03-07 18:35 UTC, tiagov8 approved these changes

2024-03-07 21:27 UTC, merged