Add Bicep User-defined Data Type Rule
SSWConsulting/SSW.Rules.Content pull request #8189
Opened 2024-03-19 07:11 UTC by ricksu978

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

PBI from SSW EagleEye project
- https://github.com/SSWConsulting/SSW.EagleEye/issues/380

> 2. What was changed?

- Added new Category "Rules to better Infrastructure as Code (IaC)"
- Added new Rule "Bicep - Do you use User-defined Data Types?"

> 3. Did you do pair or mob programming (list names)?

No

2024-03-25 00:01 UTC, wicksipedia requested changes

2024-03-25 00:01 UTC, wicksipedia commented on rules/bicep-do-you-use-user-defined-data-types/rule.md
> +## Pain
```suggestion
```

duplication of content in MS docs
pain heading doesn't add value since it includes the good example

2024-03-26 06:50 UTC, ricksu978 commented on rules/bicep-do-you-use-user-defined-data-types/rule.md
> +
bad example added

2024-03-26 06:59 UTC, ricksu978 commented on categories/software-engineering/rules-to-better-infrastructure-as-code.md
Removed IaC category
Moved new rule under Azure

2024-03-28 00:32 UTC, wicksipedia approved these changes
lgtm

2024-03-28 00:39 UTC, merged