Create Rule “method-1-using-project-reference-assemblies-within-vsnet/rule”
SSWConsulting/SSW.Rules.Content pull request #8309
Opened 2024-04-06 06:33 UTC by fenix2222

Automatically generated by Decap CMS

2024-04-07 19:28 UTC, tiagov8 commented
Hi @fenix2222 

This doesn't seem like a rule... It seems it is more like a blog post... where someone in the past tried 2 different methods to do something... 

- [ ] 1. Please check with @adamcogan if he still wants this moved as a rule

FYI - I personally would NOT migrate this. It's more noise to already too many rules.

2024-04-11 03:58 UTC, JackDevAU requested changes

2024-04-11 03:58 UTC, JackDevAU commented on rules/method-1-using-project-reference-assemblies-within-vsnet/rule.md
> +uri: method-1-using-project-reference-assemblies-within-vsnet
What is this rule 😅 @bradystroud? 

@fenix2222 can we change the uri to be a bit smaller 🙏

2024-04-13 00:44 UTC, fenix2222 commented
Closing as it is already merged here: https://github.com/SSWConsulting/SSW.Rules.Content/pull/8361

2024-04-13 00:45 UTC, closed without merging