Feat/net8 serialization
SSWConsulting/SSW.Rules.Content pull request #8549
Opened 2024-05-15 01:27 UTC by christoment

>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

Things I found during migrating TimePro to .NET 8.

> 2. What was changed?

Added rule - Do you check your API serialisation format?

> 3. Did you do pair or mob programming (list names)?
No

2024-05-15 01:32 UTC, william-liebenberg requested changes

2024-05-15 01:32 UTC, william-liebenberg commented on rules/do-you-check-your-api-serialisation-format/rule.md
> +- ⚠️ **Default serialisation proerty name casing**.
Typo: should be 'property'

2024-05-15 02:03 UTC, christoment commented on rules/do-you-check-your-api-serialisation-format/rule.md
> +- ⚠️ **Default serialisation proerty name casing**.
Fixed :)

2024-05-16 22:04 UTC, william-liebenberg approved these changes
👍

2024-05-16 23:20 UTC, jernejk approved these changes
LGTM.

The .NET Framework story is a bit less trivial because you have Katana, Owin, ASP.NET, ASP.NET Core and probably more. I remember some combination gave you camelCase by default.

I think, it's good as it is in order to not complicate it any further. 😄 (and that it slowly drifts into archive)

2024-05-16 23:26 UTC, merged