Connect on LinkedIn Update Image
SSWConsulting/SSW.Rules.Content pull request #8570
Opened 2024-05-20 14:35 UTC by tkapa

>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

✏️ Email Re: CTF - Connecting and Maintaining Connections on LinkedIn

> 2. What was changed?

✏️ Update image on the rul

> 3. Did you do pair or mob programming (list names)?

✏️

2024-05-20 17:51 UTC, tiagov8 submitted a review, later dismissed
Hi @tkapa 

- [x] File name typo, please fix!

<img width="1392" alt="Screenshot 2024-05-20 at 10 50 18 AM" src="https://github.com/SSWConsulting/SSW.Rules.Content/assets/12601228/445e0e26-c30d-4895-b3c7-f5dfddd50435">

2024-05-21 01:10 UTC, bradystroud requested changes

2024-05-21 01:10 UTC, bradystroud commented on rules/linkedin-connect-with-people/linkedin-personalie-invite.jpeg
This image is broken, please reupload

2024-05-21 07:03 UTC, bradystroud approved these changes

2024-05-21 07:03 UTC, merged