Remove [figure: old version] from rule
SSWConsulting/SSW.Rules.Content pull request #8693
Opened 2024-06-06 23:21 UTC by jaydenalchin

>
> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

Noticed myself

> 2. What was changed?

Removed old image from rule since new one is there

2024-06-06 23:25 UTC, tiagov8 commented
Hi @jaydenalchin 

I think that was left on purpose... 

- [ ] 1. Please double check with the latest people who edited this rule

2024-06-06 23:25 UTC, tiagov8 requested changes
See comment to double check the intentions for the old image

2024-06-06 23:33 UTC, SamBWagner approved these changes

2024-06-06 23:34 UTC, jaydenalchin commented
> Hi @jaydenalchin
> 
> I think that was left on purpose... although I agree with you and prefer it removed
> 
> * [x]  1. Please double check with the latest people who edited this rule

Thanks @tiagov8 I spoke with @SamBWagner and @bradystroud who both agree

2024-06-07 16:49 UTC, tiagov8 approved these changes

2024-06-07 16:50 UTC, merged