Create Rule “do-you-know-roll-forward-or-roll-backward/rule”
SSWConsulting/SSW.Rules.Content pull request #8872
Opened 2024-07-10 06:05 UTC by ozairashfaqueSSW

Automatically generated by Decap CMS

2024-07-10 21:10 UTC, tiagov8 requested changes
Hey @ozairashfaqueSSW 

- [x] 1. Please add new rule to a category

2024-07-11 02:22 UTC, ozairashfaqueSSW commented
> Hey @ozairashfaqueSSW
> 
> * [x]  1. Please add new rule to a category



I have updated the category `Rules to Better DevOps` with the new rule `Do you know when to Roll Forward and when to Roll Backward?`

2024-07-11 06:46 UTC, wicksipedia commented on rules/do-you-know-roll-forward-or-roll-backward/rule.md
> +uri: do-you-know-roll-forward-or-roll-backward
```suggestion
uri: when-to-roll-forward-or-roll-backward
```

2024-07-11 06:49 UTC, wicksipedia commented
real developers roll forward

ideally your delivery pipeline should catch catastrophic releases early on so that you don't need to roll back - especially with database changes (and potential data-loss), you need to take more things into consideration in order to support rolling back

fyi the rule feels very AI generated

2024-07-16 05:33 UTC, matt-goldman-ssw requested changes
I think this rule needs to be redrafted. We can probably dispense with the whole "when to roll forward" section and instead position the rule as saying you should always roll forward unless specifically unable to do so. And here are some examples of why you may not be able to continue forward.

2024-07-19 01:46 UTC, JackDevAU commented
**Don't forget to also fix the `uri` to match the folder name!** 

Make sure the GItHub Action: `Check-Folder-Name / rename-folder ` is  passing ✅

`rules/do-you-know-only-roll-forward`
!=
`uri: software-engineers-should-only-roll-forward`

2024-07-29 04:37 UTC, matt-goldman-ssw reviewed
LGTM

2024-07-29 06:03 UTC, tino-liu commented on rules/do-you-know-only-roll-forward/rule.md
> +tips: ""
Resolved

2024-07-29 06:05 UTC, matt-goldman-ssw approved these changes

2024-07-29 06:44 UTC, wicksipedia approved these changes

2024-07-29 16:43 UTC, merged