Fixed list to have line breaks and better positioning "/power-automate-flows-convert-timezone/rule.md"
SSWConsulting/SSW.Rules.Content pull request #9084
Opened 2024-09-01 16:38 UTC by tiagov8

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

found myself

> 2. What was changed?

Fixed list to have line breaks and better positioning

> 3. Did you do pair or mob programming (list names)?

no

2024-09-02 22:14 UTC, bradystroud requested changes
Seems wrong to strike it through... I'd rather delete it (its in source control)

If you care about the google juice, can we move it do a different rule and archive it?

2024-09-02 23:32 UTC, amankumarrr approved these changes

2024-09-03 04:47 UTC, tiagov8 commented
> Seems wrong to strike it through... I'd rather delete it (its in source control)
> 
> If you care about the google juice, can we move it do a different rule and archive it?

@bradystroud 

Agreed, but it was @adamcogan 's instructions. 

I will ask to move to a different rule and archive in the email, but I can do in another PR. Are you OK approving this one?

2024-09-03 04:53 UTC, bradystroud approved these changes

2024-09-03 04:53 UTC, merged